### ISSUE TITLE
Email v2a - spacing issue at top of the email

### ISSUE THREAD

**Issue by marinefresel** [carrot/lipton-emails#5]
Space between bottom of the image and text is too big

<img width="772" alt="screen shot 2016-03-31 at 11 31 02 am" src="https://cloud.githubusercontent.com/assets/13367288/14181214/153136a2-f734-11e5-9700-e91f1d6bbd64.png">

**Comment by maxerogers** [comment]
@marinefresel which browser and email client did this occur on?

**Comment by maxerogers** [comment]
<img width="641" alt="screen shot 2016-03-31 at 11 54 08 am" src="https://cloud.githubusercontent.com/assets/4670441/14181968/4dc43f70-f737-11e5-89ff-0d9bbde8cfa4.png">

This better?

**Comment by marinefresel** [comment]
I know you will hate that answer but I see that on the email that Kyle sent me, on Gmail

**Comment by marinefresel** [comment]
It's still a little bit bigger than the rest of the emails..

**Comment by maxerogers** [comment]
ha no hate, just need to know so I can replicate it :)

**Comment by marinefresel** [comment]
Just got a new email from Kyle, looks good to me!!! thank you Max

**Comment by kylemac** [comment]
it's listed under me, but it's @maxerogers who's doing all the work. he triggers those emails ;)

**Comment by domenicqatest** [comment]
Yes for the record... I'm the one sending the emails.  The Mail Chimp account is under Kyle's name so it'll say it's from 'Kyle', but its not.

**Comment by maxerogers** [comment]
we were both sending her emails under kyle's account :) sorry for the confusion.

**Comment by kylemac** [comment]
@marinefresel apparently everyone but me is sending these emails haha :email:

**Comment by marinefresel** [comment]
Haha good to know!!

On Thu, Mar 31, 2016 at 12:33 PM, Kyle MacDonald <notifications@github.com>
wrote:

> @marinefresel <https://github.com/marinefresel> apparently everyone but
> me is sending these emails haha [image: :email:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/carrot/lipton-emails/issues/5#issuecomment-204011505>
>



-- 
Marine Fresel
Associate Producer | Carrot Creative - A VICE Company
803 415 6507 | carrot.is/marine

**Comment by domenicqatest** [comment]
@maxerogers how are we looking on this?
