### ISSUE TITLE
Email v1b 

### ISSUE THREAD

**Issue by marinefresel** [carrot/lipton-emails#6]
The right side butts up to the right side of the screen

**Comment by domenicqatest** [comment]
@marinefresel what are you viewing the email in?  Gmail?

**Comment by marinefresel** [comment]
No, Harun is seeing that on mobile
![image1](https://cloud.githubusercontent.com/assets/13367288/14207633/5d89830e-f7e9-11e5-9892-f85d3e17679a.PNG)

**Comment by domenicqatest** [comment]
Okay I see it @marinefresel ... @maxerogers can you center the WHOLE email to guarantee it's centered for all email clients?

**Comment by maxerogers** [comment]
That is out of my control. As you can see the email has a white background behind the email. I have it set to have a yellow background for the entire email. The mail client is doing something funny. 

Marine did you forward and email you received in gmail to harun's iphone?

**Comment by marinefresel** [comment]
Yes!

On Fri, Apr 1, 2016 at 11:16 AM, Maximilian Rogers <notifications@github.com
> wrote:

> That is out of my control. As you can see the email has a white background
> behind the email. I have it set to have a yellow background for the entire
> email. The mail client is doing something funny.
>
> Marine did you forward and email you received in gmail to harun's iphone?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/carrot/lipton-emails/issues/6#issuecomment-204434819>
>



-- 
Marine Fresel
Associate Producer | Carrot Creative - A VICE Company
803 415 6507 | carrot.is/marine

**Comment by domenicqatest** [comment]
Closing this issue.
